### ISSUE TITLE
Prevent saving routePath when in stage/production

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/jore-map-ui#1055]
PRs:
https://github.com/HSLdevcom/jore-map-ui/pull/1226
https://gitlab.hsl.fi/jore/jore-map-backend/merge_requests/163
https://gitlab.hsl.fi/jore/jore-map-deploy/commit/ca874a8761d130ef1f19c6b256fe7e5822d3d9d2

TODO: at frontend stage/prod, add to routePath save button alert message "Reitinsuunnan tallentaminen  ei vielä valmis. Voit kokeilla tallentamista dev-ympäristössä. Jos haluat tallentaa reitinsuuntia tuotannossa, joudut käyttämään vanhaa JORE-ympäristöä."
+ that button could be yellow instead of green

**Comment by ahjyrkia** [comment]
Reviewed
