### ISSUE TITLE
Add isVerified group to HSL ID

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/jore-map-ui#1150]
FE PR: https://github.com/HSLdevcom/jore-map-ui/pull/1167
BE PR: https://gitlab.hsl.fi/jore/jore-map-backend/merge_requests/151

*If not verified and signing in, redirect to login page and show notification "Käyttäjätunnustasi ei ole vielä hyväksytty HSL:n puolesta."

**Comment by ahjyrkia** [comment]
Reviewed. Changes requested in BE pr

**Comment by Divinare** [comment]
Review fixes done.
