### ISSUE TITLE
Post review fixes

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/jore-map-ui#1222]
FE PR: https://github.com/HSLdevcom/jore-map-ui/pull/1223

Post review comments:

Creating new stopArea should toggle node edit on or creating new stopArea button should be disabled untill node edit is toggled on.

---

Clicking open few nodes and then spamming browser back button produces warning:

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

---

input restore fix:
https://github.com/HSLdevcom/jore-map-ui/pull/1202

---

mittaustapa change fix:
https://github.com/HSLdevcom/jore-map-ui/pull/1209

**Comment by ahjyrkia** [comment]
Reviewed and ok
