### ISSUE TITLE
Marker to its own component (NodeMarker.tsx)

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/jore-map-ui#434]
Create a reusable nodeMarker component

props: position (latLng), color (optional), onContextMenu (optional), isDraggable (optional), radius (optional), nodeType (optional)

use at routePathLinkLayer, nodeLayer, newRoutePathLayer

**Comment by kronken** [comment]
Hmm, maybe, in which way would this be different from the react-leaflet marker component we are using already?

**Comment by kronken** [comment]
The react leaflet marker contains parameters such as position, onContextMenu, draggable...
