### ISSUE TITLE
Refactoring (renaming variables, sidebarStore fix etc.)

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/jore-map-ui#51]
- [x] move showLogin into store
- [x] rename: EditableLines -> LineEditView
- [x] TransitToggleButton, rename: handleClick -> toggleActivity (reason: rename functions so that they describe what they do)
- [x] TransitToggleButton: fix: className={this.toggleClass()} with: className={`transit-toggle ${this.props.toggled ? this.state.type : 'toggled'}`}
- [x] LineItem fix: handleLineSelected -> selectLine
- [x] rename: handleModalLoginButton
- [x] Fix events: (event: any): void --> mouse event
- [x] rename: setSelectedLine --> addLineToSelection / addSelectedLine / selectLine
- [x]  start using:
    set filters(filters: string[]) {
        this._filters = filters
    }

**Comment by neodyymi** [comment]
https://mobx.js.org/best/react-performance.html#render-lists-in-dedicated-components
