### ISSUE TITLE
Redirect user back to origin after login

### ISSUE THREAD

**Issue by kronken** [HSLdevcom/jore-map-ui#653]

**Comment by Divinare** [comment]
To implement this:

1. user goes http://localhost:3000/routes/?routes[0]=0033
2. save that link (http://localhost:3000/routes/?routes[0]=0033)
3. user is redirected to /login
4. put that saved link to this url:
window.location.replace(
`https://hslid-uat.cinfra.fi/openid/auth?client_id=6549375356227079&redirect_uri=${constants.AFTER_LOGIN_URL}&response_type=code&scope=email+https://oneportal.trivore.com/scope/groups.readonly`
)
5. when user gets redirected back to our app, get the saved link from afterLogin url and redirect to that url

look at my comment here: https://github.com/HSLdevcom/jore-map-ui/pull/687/files#diff-c8a101915dc6871f1f3d7ad2208d8655R67

add that saved link to that redirect call
