### ISSUE TITLE
Get username from jr_kayttaja table and use that when saving

### ISSUE THREAD

**Issue by Divinare** [HSLdevcom/jore-map-ui#663]
FE PR: https://github.com/HSLdevcom/jore-map-ui/pull/903
BE PR: https://gitlab.hsl.fi/jore/jore-map-backend/merge_requests/67

When signing in and user has write access, backend tries to get user with hsl-id account's email address
* if email is not found, redirect user to login page and show error to the user "Kirjautuminen epäonnistui, sähköpostiosoitteen omaavaa käyttäjätunnusta ei löytynyt joukkoliikennerekisterin tietokannasta. Ota yhteyttä käyttäjätunnusten hallinnoijaan."

**Comment by kronken** [comment]
We should definitely not send modified by to the backend. That would create critical problems when people could fake who made changes, which would allow sabotage.
