### ISSUE TITLE
Prevent user from having her session expired while using the application

### ISSUE THREAD

**Issue by kronken** [HSLdevcom/jore-map-ui#707]
One solution would be to have the session expiration time to roughly 4 hours, and update this value every time the backend gets a call.

- Current implementation seems to do this automatically
https://gitlab.hsl.fi/jore/jore-map-backend/merge_requests/36

FE:
https://github.com/HSLdevcom/jore-map-ui/pull/769

BE:
https://gitlab.hsl.fi/jore/jore-map-backend/merge_requests/36

**Comment by Divinare** [comment]
What if user could be redirected to /login page if he gets "forbidden" from some operation?

Use he same code as in logout?
        this.props.loginStore!.clear();
        const loginLink = routeBuilder.to(SubSites.login).clear().toLink();
        navigator.goTo(loginLink);
